# ./.tmuxinator-light.yml

name: cli-talk
root: .

on_project_start: ~/.config/ranger/switch-to-kitty-light.sh

on_project_stop: ~/.config/ranger/switch-to-default-dark.sh
on_project_exit: ~/.config/ranger/switch-to-default-dark.sh

pre_window: alias lc='llc' && alias bat='bat --theme=GitHub'

tmux_command: byobu

windows:
    - empty:
        - cd ~
        - clear
        - echo -e "\nHallo Softwerkskammer" | boxes -d peek -a hcvc
    - ranger:
        - cd ~
        - clear
        - echo -e "\nranger" | boxes -d peek -a hcvc
    - bat:
        - clear
        - echo -e "\nbat slides.md" | boxes -d peek -a hcvc
    - (porn) colorls:
        - clear
        - echo -e "\nlc" | boxes -d peek -a hcvc
    - (porn) lolcat:
        - clear
        - echo -e "\nla | lolcat" | boxes -d peek -a hcvc
    - (porn) no-more-secrets:
        - clear
        - echo -e "\nla | nms | lolcat" | boxes -d peek -a hcvc
    - christmas-tree:
        - clear
        - ./christmas-tree.sh
