# ./.tmuxinator-light.yml

name: cli-talk
root: .

on_project_start: ~/.config/ranger/switch-to-kitty-light.sh

on_project_stop: ~/.config/ranger/switch-to-default-dark.sh
on_project_exit: ~/.config/ranger/switch-to-default-dark.sh

pre_window: alias lc='llc' && alias bat='bat --theme=GitHub'

tmux_command: byobu

windows:
    - empty:
        - cd ~
        - clear
        - echo -e "\nHallo Softwerkskammer\n" | boxes -d peek -a c
    - ranger:
        - cd ~
        - clear
        - echo -e "\nranger\n" | boxes -d peek -a c
    - bat:
        - clear
        - echo -e "\nbat slides.md\n" | boxes -d peek -a c
    - (porn) colorls:
        - clear
        - echo -e "\nlc\n" | boxes -d peek -a c
    - (porn) lolcat:
        - clear
        - echo -e "\nla | lolcat\n" | boxes -d peek -a c
    - (porn) no-more-secrets:
        - clear
        - echo -e "\nla | nms | lolcat\n" | boxes -d peek -a c
    - christmas-tree:
        - clear
        - ./christmas-tree.sh
